[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['solady/=lib/solady/src/', 'solarray/=lib/solarray/src/']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
